# Generated by Django 5.1.4 on 2024-12-25 18:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_manzil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('malumot', ckeditor.fields.RichTextField()),
                ('aholi_soni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aholisonlari')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hududnomlari')),
            ],
        ),
    ]
