# Generated by Django 5.1.3 on 2025-01-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hudud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hudud',
            name='aholi_soni',
        ),
        migrations.RemoveField(
            model_name='hudud',
            name='hudud',
        ),
        migrations.DeleteModel(
            name='AholiSonlari',
        ),
        migrations.DeleteModel(
            name='Hudud',
        ),
        migrations.DeleteModel(
            name='HududNomlari',
        ),
    ]
