# Generated by Django 5.1.3 on 2025-03-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_testlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='course/'),
        ),
        migrations.AddField(
            model_name='maruza',
            name='file',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taqdimot',
            name='file',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
