# Generated by Django 5.1.3 on 2025-05-07 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course_image_maruza_file_taqdimot_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('thema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
